###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Marcos",
    "email": "marcos@gmail.com",
    "senha": "1234"
}

###

PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "adm",
    "email": "adm@gmail.com",
    "senha": "1234"
}

###

DELETE  http://localhost:3000/usuarios/4




###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "adm@gmail.com",
    "senha": "1234"
}