###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Marcos",
    "senha": "1234"
}

###

PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "Puta",
    "senha": "1234"
}

###

DELETE  http://localhost:3000/usuarios/2
Content-Type: application/json

{}